apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: modresorts-ingress
  namespace: modresorts
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: modresorts.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: modresorts-service
                port:
                  number: 80
