apiVersion: v1
kind: Service
metadata:
  name: modresorts-service
  namespace: modresorts
  labels:
    app: modresorts
spec:
  type: ClusterIP
  selector:
    app: modresorts
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
